---
- hosts: all
  sudo: true
  vars:
    web_server: apachephp
    servername: vagrant.dev www.vagrant.dev 192.168.33.99
    timezone: America/Kentucky/Louisville
  vars_files:
    - vars/mysql.yml
    - vars/common.yml
    - [ "vars/apachephp.yml", "vars/ws_defaults.yml" ]
  roles:
    - init
    - php5-cli
    - apache
    - php5
    - mysql
    - composer
    - phpcommon
    - app
